-- 使用案例
-- 若success为true，result为try返回值，若success为false，result为错误信息
-- local result = try {
-- 	function (param1,param2)         -- 必须存在
-- 		error("123")    -- 主动抛出异常
-- 	end,
-- 	catch = function (error,param1,param2)       -- 异常捕获 可缺省
-- 		print(error)
-- 	end,
-- 	finally = function (success,result,param1,param2)      -- 必然执行 可缺省
-- 		print(success,result)
-- 	end,
--  param1,param2
-- }
-- print(result);

return function(block)
    local tryFunc = block[1]
    local catchFunc = block['catch']
    local finallyFunc = block['finally']

    local params = {}
    if #block > 0 then
    	for i = 2, #block do
    		table.insert(params, block[i])
    	end
    end

    local success, result = pcall(tryFunc,unpack(params))

    if not success and catchFunc then
        catchFunc(result,unpack(params))
    end

    if finallyFunc then
        finallyFunc(success, result,unpack(params))
    end

    if success then
        return result
    end
end
